language: node_js
sudo: false
node_js:
  - 11
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local-dir: public
  committer-from-gh: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master